# Generated by Django 3.2.3 on 2021-08-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='portal',
            field=models.CharField(choices=[('ndtv.com', 'ndtv.com'), ('soundcloud.com', 'soundcloud.com'), ('https://www.amazon.in', 'https://www.amazon.in'), ('https://internshala.com', 'https://internshala.com')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
